Repository rising-jun/swift-starbucks, pull requests merged in 2022-05, with the labels that each got.

#3 [init] 프로젝트 초기설정 완료
  StarbucksClone/StarbucksClone.xcodeproj/project.pbxproj
  StarbucksClone/StarbucksClone.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  StarbucksClone/StarbucksClone.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  StarbucksClone/StarbucksClone/AppDelegate.swift
  StarbucksClone/StarbucksClone/Assets.xcassets/AccentColor.colorset/Contents.json
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/Contents.json
  StarbucksClone/StarbucksClone/Assets.xcassets/Contents.json
  StarbucksClone/StarbucksClone/Base.lproj/LaunchScreen.storyboard
  StarbucksClone/StarbucksClone/Info.plist
  StarbucksClone/StarbucksClone/LoginViewController.swift
  StarbucksClone/StarbucksClone/SceneDelegate.swift
  StarbucksClone/StarbucksCloneTests/StarbucksCloneTests.swift
  StarbucksClone/StarbucksCloneUITests/StarbucksCloneUITests.swift
  StarbucksClone/StarbucksCloneUITests/StarbucksCloneUITestsLaunchTests.swift
Labels: Init

#10 Feature-7
  StarbucksClone/StarbucksClone.xcodeproj/project.pbxproj
  StarbucksClone/StarbucksClone/Assets.xcassets/eventImage.imageset/1627033273796event-bg.png
  StarbucksClone/StarbucksClone/Assets.xcassets/eventImage.imageset/1627033273796event-bg@2x.png
  StarbucksClone/StarbucksClone/Assets.xcassets/eventImage.imageset/1627033273796event-bg@3x.png
  StarbucksClone/StarbucksClone/Assets.xcassets/eventImage.imageset/Contents.json
  StarbucksClone/StarbucksClone/Controller/EventViewController.swift
  StarbucksClone/StarbucksClone/Extension/UIColor+.swift
  StarbucksClone/StarbucksClone/Model/Repository/EventRepository.swift
  StarbucksClone/StarbucksClone/Model/Service/CodeSquadStarbuckstAPI.swift
  StarbucksClone/StarbucksClone/Model/Service/EventService.swift
  StarbucksClone/StarbucksClone/Model/StarbuckstDTO.swift
  StarbucksClone/StarbucksClone/Model/UseCase/EventUseCase.swift
  StarbucksClone/StarbucksClone/Model/UseCase/SceneUseCase.swift
  StarbucksClone/StarbucksClone/SceneDelegate.swift
  StarbucksClone/StarbucksClone/View/EventView.swift
Labels: feature

#11 Feature 4
  StarbucksClone/StarbucksClone.xcodeproj/project.pbxproj
  StarbucksClone/StarbucksClone/Assets.xcassets/kakaoLogo.imageset/Contents.json
  StarbucksClone/StarbucksClone/Assets.xcassets/kakaoLogo.imageset/kakaoLogo.png
  StarbucksClone/StarbucksClone/Assets.xcassets/kakaoLogo.imageset/kakaoLogo@2x.png
  StarbucksClone/StarbucksClone/Assets.xcassets/kakaoLogo.imageset/kakaoLogo@3x.png
  StarbucksClone/StarbucksClone/Controller/EventViewController.swift
  StarbucksClone/StarbucksClone/Controller/HomeViewController.swift
  StarbucksClone/StarbucksClone/Controller/LoginViewController.swift
  StarbucksClone/StarbucksClone/Model/Entity/UserData.swift
  StarbucksClone/StarbucksClone/Model/UseCase/LoginUseCase.swift
  StarbucksClone/StarbucksClone/SceneDelegate.swift
  StarbucksClone/StarbucksClone/View/EventView.swift
  StarbucksClone/StarbucksClone/View/LoginView.swift
Labels: feature

#13 Feature 7
  StarbucksClone/StarbucksClone.xcodeproj/project.pbxproj
  StarbucksClone/StarbucksClone/AppDelegate.swift
  StarbucksClone/StarbucksClone/Controller/EventViewController.swift
  StarbucksClone/StarbucksClone/Controller/HomeViewController.swift
  StarbucksClone/StarbucksClone/Controller/LoginViewController.swift
  StarbucksClone/StarbucksClone/Model/Entity/ViewControllerComponents.swift
  StarbucksClone/StarbucksClone/Model/UseCase/EventUseCase.swift
  StarbucksClone/StarbucksClone/Model/UseCase/LoginUseCase.swift
  StarbucksClone/StarbucksClone/Model/UseCase/SceneUseCase.swift
  StarbucksClone/StarbucksClone/SceneDelegate.swift
Labels: feature

#15 Refactor 14
  StarbucksClone/StarbucksClone.xcodeproj/project.pbxproj
  StarbucksClone/StarbucksClone.xcodeproj/xcshareddata/xcschemes/StarbucksClone.xcscheme
  StarbucksClone/StarbucksClone/AppDelegate.swift
  StarbucksClone/StarbucksClone/Controller/EventViewController.swift
  StarbucksClone/StarbucksClone/Controller/LoginViewController.swift
  StarbucksClone/StarbucksClone/Dependency/DependencyInjector.swift
  StarbucksClone/StarbucksClone/Dependency/EventDependency.swift
  StarbucksClone/StarbucksClone/Dependency/LoginDependency.swift
  StarbucksClone/StarbucksClone/Dependency/SceneDependency.swift
  StarbucksClone/StarbucksClone/Model/KakaoLogin.swift
  StarbucksClone/StarbucksClone/Model/Repository/EventRepository.swift
  StarbucksClone/StarbucksClone/Model/Service/EventService.swift
  StarbucksClone/StarbucksClone/Model/UseCase/EventUseCase.swift
  StarbucksClone/StarbucksClone/Model/UseCase/LoginUseCase.swift
  StarbucksClone/StarbucksClone/Model/UseCase/SceneUseCase.swift
  StarbucksClone/StarbucksClone/Model/UserDefaultManager.swift
  StarbucksClone/StarbucksClone/SceneDelegate.swift
  StarbucksClone/StarbucksCloneTests/Mock/EventRepositoryStub.swift
  StarbucksClone/StarbucksCloneTests/Mock/KakaoLoginStub.swift
  StarbucksClone/StarbucksCloneTests/StarbucksCloneTests.swift
Labels: feature

#16 Feature 12
  StarbucksClone/StarbucksClone.xcodeproj/project.pbxproj
  StarbucksClone/StarbucksClone.xcodeproj/xcshareddata/xcschemes/StarbucksClone.xcscheme
  StarbucksClone/StarbucksClone/Assets.xcassets/gucci.imageset/Contents.json
  StarbucksClone/StarbucksClone/Assets.xcassets/gucci.imageset/스크린샷 2022-04-26 오후 5.15.30.png
  StarbucksClone/StarbucksClone/Controller/HomeViewController.swift
  StarbucksClone/StarbucksClone/Controller/WhatsNewViewController.swift
  StarbucksClone/StarbucksClone/Extension/UIView.swift
  StarbucksClone/StarbucksClone/Model/DTO/BeverageImageDTO.swift
  StarbucksClone/StarbucksClone/Model/DTO/BeverageInfoDTO.swift
  StarbucksClone/StarbucksClone/Model/DTO/HomeComponentsDTO.swift
  StarbucksClone/StarbucksClone/Model/DTO/HomeEventDTO.swift
  StarbucksClone/StarbucksClone/Model/DTO/WhatsNewEventDTO.swift
  StarbucksClone/StarbucksClone/Model/Entity/HomeComponents.swift
  StarbucksClone/StarbucksClone/Model/Entity/HomeEventDescription.swift
  StarbucksClone/StarbucksClone/Model/Entity/ProductDescription.swift
  StarbucksClone/StarbucksClone/Model/Entity/WhatsNewEventDescription.swift
  StarbucksClone/StarbucksClone/Model/Repository/HomeRepository.swift
  StarbucksClone/StarbucksClone/Model/Repository/WhatsNewRepository.swift
  StarbucksClone/StarbucksClone/Model/Service/EventService.swift
  StarbucksClone/StarbucksClone/Model/Service/HomeAPI.swift
  StarbucksClone/StarbucksClone/Model/Service/HomeService.swift
  StarbucksClone/StarbucksClone/Model/Service/WhatsNewService.swift
  StarbucksClone/StarbucksClone/Model/UseCase/HomeUseCase.swift
  StarbucksClone/StarbucksClone/Model/UseCase/WhatsNewUseCase.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/HomeEventCollectionCell.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/HomeEventCollectionDataSource.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/HomeScrollViewDelegate.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/RecommendCollectionDataSource.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/RecommendCollectionDelegate.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/RecommendDTO.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/RecommentCollectionCell.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/WhatsNewCollectionCell.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/WhatsNewCollectionDataSource.swift
  StarbucksClone/StarbucksClone/View/HomeView.swift
  StarbucksClone/StarbucksClone/View/WhatsNewTitleView.swift
  StarbucksClone/StarbucksClone/View/WhatsNewView.swift
Labels: feature

#17 Feature 12-2
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/100.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/1024.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/114.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/120.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/144.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/152.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/167.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/180.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/20.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/29.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/40.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/50.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/57.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/58.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/60.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/72.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/76.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/80.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/87.png
  StarbucksClone/StarbucksClone/Assets.xcassets/AppIcon.appiconset/Contents.json
  StarbucksClone/StarbucksClone/Assets.xcassets/gucci.imageset/Contents.json
  StarbucksClone/StarbucksClone/Assets.xcassets/gucci.imageset/스크린샷 2022-04-26 오후 5.15.30.png
  StarbucksClone/StarbucksClone/Controller/HomeViewController.swift
  StarbucksClone/StarbucksClone/Controller/WhatsNewViewController.swift
  StarbucksClone/StarbucksClone/Model/Entity/WhatsNewEventDescription.swift
  StarbucksClone/StarbucksClone/Model/Repository/WhatsNewRepository.swift
  StarbucksClone/StarbucksClone/Model/Service/WhatsNewService.swift
  StarbucksClone/StarbucksClone/Model/UseCase/WhatsNewUseCase.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/WhatsNewCollectionCell.swift
  StarbucksClone/StarbucksClone/View/CollectionDelegate/WhatsNewCollectionDataSource.swift
Labels: refactor
